package relay.terminal.linux

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import org.connectbot.terminal.CellRun
import org.connectbot.terminal.CursorPosition
import org.connectbot.terminal.ScreenCell
import org.connectbot.terminal.TermRect
import org.connectbot.terminal.TerminalCallbacks
import org.connectbot.terminal.TerminalNative
import org.connectbot.terminal.TerminalProperty
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Desktop terminal emulator: libvterm through termlib's JNI bridge, with a
 * grid snapshot Compose can render.
 *
 * **This is deliberately NOT a port of termlib's `TerminalEmulator.kt`.** That
 * file is 1,518 lines because it is built to run inside an Android *Service*:
 * Handler/Looper hops, Choreographer frame sync, StateFlow snapshot machinery
 * for a background process, OSC 8 hyperlink tracking, and semantic prompt
 * regions. A relay client needs none of that — it needs bytes in, a grid out,
 * and keystrokes back. Writing the ~300 lines we actually need against the
 * `TerminalNative` boundary is smaller, testable, and avoids inheriting
 * Android's threading model on a platform that does not have it.
 *
 * ### The deadlock rule
 *
 * termlib is explicit: *"Callbacks MUST NOT call back into Terminal methods
 * (will deadlock)"* — the native side holds a non-reentrant mutex across the
 * upcall. So [damage] records a dirty region and returns immediately; the grid
 * is read afterwards, outside the callback, by [refreshIfDirty]. This is the
 * same constraint Android solves with Handler+Choreographer; on desktop the
 * renderer's own frame loop drives it instead, which is simpler and has no
 * platform dependency.
 */
class LinuxTerminalEmulator(
    initialRows: Int = 24,
    initialCols: Int = 80,
    palette: IntArray? = null,
    defaultForeground: Int = 0xFFFFFFFF.toInt(),
    defaultBackground: Int = 0xFF000000.toInt(),
    /**
     * Emulator → relay. Keystrokes and any escape sequences libvterm generates.
     *
     * Optional at construction and replaceable via [setInputSink] because the
     * emulator is built before `RelayTerminalController` installs its own sink.
     * Bytes produced before a sink exists are dropped rather than buffered:
     * pre-attach keystrokes have nowhere legitimate to go, and replaying them
     * later would inject stale input at whatever prompt happened to be current.
     */
    onKeyboardInput: ((ByteArray) -> Unit)? = null,
    private val onBell: (() -> Unit)? = null,
    /** OSC 52 clipboard writes from the host (tmux/vim/kitty copies). */
    private val onClipboardCopy: ((String) -> Unit)? = null,
    private val onTitleChange: ((String) -> Unit)? = null,
) : AutoCloseable {

    /**
     * Current sink for emulator-generated bytes. Volatile because libvterm can
     * fire `onKeyboardInput` from whichever thread called into it, while the
     * sink is installed from the UI thread.
     */
    @Volatile
    private var inputSink: ((ByteArray) -> Unit)? = onKeyboardInput

    /** Installs (or replaces) the emulator → relay byte sink. */
    fun setInputSink(sink: ((ByteArray) -> Unit)?) {
        inputSink = sink
    }

    @Volatile
    private var rows: Int = initialRows

    @Volatile
    private var cols: Int = initialCols

    /** Set by [damage]; cleared by [refreshIfDirty]. */
    private val dirty = AtomicBoolean(true)

    private val cursor = MutableStateFlow(GridCursor(0, 0, visible = true))

    /** Latest renderable grid. Compose collects this. */
    private val _grid = MutableStateFlow(TerminalGrid.empty(initialRows, initialCols))
    val grid: StateFlow<TerminalGrid> = _grid.asStateFlow()

    /** Whether the alternate screen buffer is active (Claude Code runs in it). */
    private val _altScreen = MutableStateFlow(false)
    val altScreen: StateFlow<Boolean> = _altScreen.asStateFlow()

    /**
     * Mouse tracking mode the running program asked for. Non-zero means the
     * program wants wheel and click reports — the thing Android's engine cannot
     * send at all, and which iOS had to fake by hand.
     */
    private val _mouseMode = MutableStateFlow(0)
    val mouseMode: StateFlow<Int> = _mouseMode.asStateFlow()

    private val callbacks = object : TerminalCallbacks {
        override fun damage(startRow: Int, endRow: Int, startCol: Int, endCol: Int): Int {
            // MUST NOT touch the native terminal here — see the class doc.
            dirty.set(true)
            return 1
        }

        override fun moverect(dest: TermRect, src: TermRect): Int {
            dirty.set(true)
            return 1
        }

        override fun moveCursor(pos: CursorPosition, oldPos: CursorPosition, visible: Boolean): Int {
            cursor.value = GridCursor(pos.row, pos.col, visible)
            dirty.set(true)
            return 1
        }

        override fun setTermProp(prop: Int, value: TerminalProperty): Int {
            when (prop) {
                PROP_TITLE -> (value as? TerminalProperty.StringValue)?.let { onTitleChange?.invoke(it.value) }
                PROP_ALTSCREEN -> (value as? TerminalProperty.BoolValue)?.let { _altScreen.value = it.value }
                PROP_MOUSE -> (value as? TerminalProperty.IntValue)?.let { _mouseMode.value = it.value }
                PROP_CURSORVISIBLE -> (value as? TerminalProperty.BoolValue)?.let {
                    cursor.value = cursor.value.copy(visible = it.value)
                }
            }
            return 1
        }

        override fun bell(): Int {
            onBell?.invoke()
            return 1
        }

        // Local scrollback is not retained here: the SERVER's RingBuffer is the
        // authoritative scrollback and replays on reattach, so keeping a second
        // copy on the client would only add memory and a chance to disagree.
        override fun pushScrollbackLine(cols: Int, cells: Array<ScreenCell>, softWrapped: Boolean): Int = 1

        override fun popScrollbackLine(cols: Int, cells: Array<ScreenCell>): Int = 0

        override fun clearScrollback(): Int = 1

        override fun onKeyboardInput(data: ByteArray): Int {
            inputSink?.invoke(data)
            return 1
        }

        override fun onOscSequence(command: Int, payload: String, cursorRow: Int, cursorCol: Int): Int {
            // OSC 52 = clipboard. The server already strips terminal *queries*
            // (TerminalQueryFilter) so nothing here needs to answer one.
            if (command == OSC_CLIPBOARD) {
                decodeOsc52(payload)?.let { onClipboardCopy?.invoke(it) }
            }
            return 1
        }
    }

    private val native: TerminalNative

    init {
        NativeLibraryLoader.ensureLoaded()
        native = TerminalNative(callbacks)
        native.resize(initialRows, initialCols)
        native.setDefaultColors(defaultForeground, defaultBackground)
        palette?.let { native.setPaletteColors(it, it.size.coerceAtMost(16)) }
        refreshIfDirty()
    }

    /** Relay → emulator. Bytes are fed verbatim; no String round-trip. */
    fun feedOutput(bytes: ByteArray, offset: Int = 0, length: Int = bytes.size - offset) {
        if (length <= 0) return
        synchronized(this) { native.writeInput(bytes, offset, length) }
    }

    fun resize(newRows: Int, newCols: Int) {
        if (newRows <= 0 || newCols <= 0) return
        if (newRows == rows && newCols == cols) return
        synchronized(this) { native.resize(newRows, newCols) }
        rows = newRows
        cols = newCols
        dirty.set(true)
    }

    /** Applies a 16-colour ANSI palette plus default fg/bg (e.g. from the Omarchy theme). */
    fun applyPalette(ansi: IntArray, foreground: Int, background: Int) {
        synchronized(this) {
            native.setPaletteColors(ansi, ansi.size.coerceAtMost(16))
            native.setDefaultColors(foreground, background)
        }
        dirty.set(true)
    }

    /** A typed character. [modifiers] is 1=Shift, 2=Alt, 4=Ctrl. */
    fun dispatchCharacter(codepoint: Int, modifiers: Int = 0) {
        synchronized(this) { native.dispatchCharacter(modifiers, codepoint) }
    }

    /** A special key (arrows, Home, F-keys…) as a `VTermKey` value. */
    fun dispatchKey(key: Int, modifiers: Int = 0) {
        synchronized(this) { native.dispatchKey(modifiers, key) }
    }

    /**
     * Reports a wheel notch at the given cell.
     *
     * [down] false scrolls up. libvterm encodes the report in whatever mode the
     * running program set (X10 / SGR / urxvt) and emits nothing at all when the
     * program has not enabled mouse reporting — so a plain shell is unaffected
     * and needs no guard here.
     *
     * This is what makes an agent transcript scrollable. Claude Code runs in the
     * alternate screen buffer, which has no scrollback by definition: the
     * viewport is not what moves, the program's own transcript is, and it only
     * moves when told. iOS had to hand-roll SGR wheel reports to achieve this;
     * Android has no mouse path at all and still cannot do it.
     */
    fun dispatchWheel(down: Boolean, row: Int, col: Int, modifiers: Int = 0) {
        // Buttons 4/5 are wheel up/down by X11 convention — the same encoding
        // the macOS client's scrollWheel already sends.
        val button = if (down) 5 else 4
        synchronized(this) {
            // MUST move first. `vterm_mouse_button` reports libvterm's CURRENT
            // pointer position, which only `vterm_mouse_move` updates — without
            // this every wheel event reported cell (1,1) regardless of where the
            // pointer actually was, so any program that hit-tests the wheel
            // (tmux panes, a TUI's list under the cursor) would scroll the wrong
            // thing. Caught by MouseDispatchTest asserting on the reported cell.
            native.dispatchMouseMove(row, col, modifiers)
            native.dispatchMouseButton(button, true, modifiers)
            // Wheels have no physical release, but libvterm's SGR encoder emits
            // a release event for the press it just saw; sending it keeps the
            // stream well-formed for programs that track button state.
            native.dispatchMouseButton(button, false, modifiers)
        }
    }

    /** Reports a mouse move to the cell at [row]/[col]. */
    fun dispatchMouseMove(row: Int, col: Int, modifiers: Int = 0) {
        synchronized(this) { native.dispatchMouseMove(row, col, modifiers) }
    }

    /** Reports a press or release of [button] (0 = left, 1 = middle, 2 = right). */
    fun dispatchMouseButton(button: Int, pressed: Boolean, modifiers: Int = 0) {
        synchronized(this) { native.dispatchMouseButton(button, pressed, modifiers) }
    }

    /**
     * Rebuilds the grid snapshot when something changed. Returns true if the
     * grid was replaced.
     *
     * Called from the renderer's frame loop, never from a callback. Reading the
     * whole visible grid rather than only the damaged region is a deliberate
     * simplification: at 200x60 that is 12,000 cells fetched in run-batches, far
     * cheaper than a frame, and it removes an entire class of "damage tracking
     * disagreed with reality" bugs.
     */
    fun refreshIfDirty(): Boolean {
        if (!dirty.compareAndSet(true, false)) return false
        val snapshot = synchronized(this) { readGrid() }
        _grid.value = snapshot
        return true
    }

    private fun readGrid(): TerminalGrid {
        val r = rows
        val c = cols
        val lines = ArrayList<GridLine>(r)
        val run = CellRun()

        for (row in 0 until r) {
            val spans = ArrayList<GridSpan>()
            var col = 0
            while (col < c) {
                run.reset()
                val cells = native.getCellRun(row, col, run)
                if (cells <= 0) {
                    // Defensive: a zero-length run would spin forever.
                    col++
                    continue
                }
                spans += GridSpan(
                    text = String(run.chars, 0, charCountFor(run, cells)),
                    columns = cells,
                    fg = packRgb(run.fgRed, run.fgGreen, run.fgBlue),
                    bg = packRgb(run.bgRed, run.bgGreen, run.bgBlue),
                    bold = run.bold,
                    italic = run.italic,
                    underline = run.underline,
                    reverse = run.reverse,
                    strike = run.strike,
                    blink = run.blink,
                )
                col += cells
            }
            lines += GridLine(spans, continuation = runCatching { native.getLineContinuation(row) }.getOrDefault(false))
        }
        return TerminalGrid(rows = r, cols = c, lines = lines, cursor = cursor.value)
    }

    /**
     * `CellRun.chars` is a fixed 256-entry buffer and upstream's
     * `getCharsAsString()` stringifies all of it, trailing NULs included. The
     * native side fills only the leading portion, so we find the real end
     * ourselves: scan to the first NUL, bounded by the buffer.
     *
     * Character count is not the same as [cells] — a wide (CJK) glyph occupies
     * two columns but one char, and a combining mark adds chars without adding
     * columns — so it cannot simply be derived from the run length.
     */
    private fun charCountFor(run: CellRun, cells: Int): Int {
        val max = run.chars.size
        var n = 0
        // NUL, not space: a space is legitimate cell content, and terminating
        // on one would truncate every run at its first blank.
        while (n < max && run.chars[n] != '\u0000') n++
        return n
    }

    private fun packRgb(r: Int, g: Int, b: Int): Int =
        (0xFF shl 24) or ((r and 0xFF) shl 16) or ((g and 0xFF) shl 8) or (b and 0xFF)

    override fun close() {
        synchronized(this) { native.close() }
    }

    companion object {
        // VTermProp values, transcribed from vterm.h (libvterm 0.3.3). Kept as
        // constants rather than an enum so a future libvterm addition cannot
        // throw on an unknown property.
        //
        // The enum is implicitly numbered, so these MUST be counted from the
        // header rather than guessed — ALTSCREEN was initially wrong here (5,
        // which is actually ICONNAME), and the only symptom was that alt-screen
        // detection silently never fired. That matters: Claude Code runs in the
        // alternate buffer, so the flag drives whether local scrollback exists.
        //   1 CURSORVISIBLE   2 CURSORBLINK   3 ALTSCREEN   4 TITLE
        //   5 ICONNAME        6 REVERSE       7 CURSORSHAPE 8 MOUSE
        private const val PROP_CURSORVISIBLE = 1
        private const val PROP_ALTSCREEN = 3
        private const val PROP_TITLE = 4
        private const val PROP_MOUSE = 8

        private const val OSC_CLIPBOARD = 52

        /**
         * Decodes an OSC 52 payload (`<selection>;<base64>`).
         *
         * A `?` payload is a clipboard *read request*; it is ignored so a remote
         * program can never exfiltrate the local clipboard — the same rule the
         * server's `OSC52Parser` applies.
         */
        internal fun decodeOsc52(payload: String): String? {
            val sep = payload.indexOf(';')
            if (sep < 0) return null
            val data = payload.substring(sep + 1)
            if (data == "?" || data.isEmpty()) return null
            return runCatching {
                String(java.util.Base64.getDecoder().decode(data), Charsets.UTF_8)
            }.getOrNull()
        }
    }
}

/** Cursor position and visibility within the grid. */
data class GridCursor(val row: Int, val col: Int, val visible: Boolean)

/** A run of identically-styled cells. Colours are packed opaque ARGB. */
data class GridSpan(
    val text: String,
    val columns: Int,
    val fg: Int,
    val bg: Int,
    val bold: Boolean = false,
    val italic: Boolean = false,
    val underline: Int = 0,
    val reverse: Boolean = false,
    val strike: Boolean = false,
    val blink: Boolean = false,
)

/** One screen row. [continuation] marks a soft-wrapped line. */
data class GridLine(val spans: List<GridSpan>, val continuation: Boolean = false)

/** An immutable snapshot of the visible screen, safe to hand to Compose. */
data class TerminalGrid(
    val rows: Int,
    val cols: Int,
    val lines: List<GridLine>,
    val cursor: GridCursor,
) {
    companion object {
        fun empty(rows: Int, cols: Int) = TerminalGrid(
            rows = rows,
            cols = cols,
            lines = List(rows) { GridLine(emptyList()) },
            cursor = GridCursor(0, 0, visible = true),
        )
    }
}
