#!/usr/bin/env python3
"""Adds mouse dispatch to the pinned termlib checkout.

See 0001-mouse-dispatch.md for the rationale. Idempotent: re-running against an
already-patched tree is a no-op, so the Gradle task can be up-to-date checked
and a partial build never double-applies.
"""
import sys, pathlib

root = pathlib.Path(sys.argv[1])
cpp = root / "lib/src/main/cpp"
kt = root / "lib/src/main/java/org/connectbot/terminal"

MOD_DECODE = """    VTermModifier mod = VTERM_MOD_NONE;
    if (modifiers & 1) mod = (VTermModifier)(mod | VTERM_MOD_SHIFT);
    if (modifiers & 2) mod = (VTermModifier)(mod | VTERM_MOD_ALT);
    if (modifiers & 4) mod = (VTermModifier)(mod | VTERM_MOD_CTRL);
"""

def patch(path, anchor, addition, marker):
    p = pathlib.Path(path)
    s = p.read_text()
    if marker in s:
        return False
    if anchor not in s:
        raise SystemExit(f"anchor not found in {p.name}: {anchor[:60]!r}")
    p.write_text(s.replace(anchor, anchor + addition, 1))
    return True

changed = []

# --- Terminal.h: declare beside the existing dispatchers -------------------
if patch(
    cpp / "Terminal.h",
    "    bool dispatchCharacter(int modifiers, int codepoint);",
    """
    // CodeRelay addition — see linux-terminal/patches/0001-mouse-dispatch.md.
    bool dispatchMouseMove(int row, int col, int modifiers);
    bool dispatchMouseButton(int button, bool pressed, int modifiers);""",
    "dispatchMouseMove",
):
    changed.append("Terminal.h")

# --- Terminal.cpp: implementations + JNI entry points ----------------------
impl = f"""

// CodeRelay addition — see linux-terminal/patches/0001-mouse-dispatch.md.
// libvterm owns the current mouse mode and encodes the report (X10 / SGR /
// urxvt) accordingly; we only hand it the event. Generated bytes leave through
// the existing onKeyboardInput callback.
bool Terminal::dispatchMouseMove(int row, int col, int modifiers) {{
    std::scoped_lock lock(mLock);
    if (!mVt) {{
        return false;
    }}
{MOD_DECODE}    vterm_mouse_move(mVt, row, col, mod);
    return true;
}}

bool Terminal::dispatchMouseButton(int button, bool pressed, int modifiers) {{
    std::scoped_lock lock(mLock);
    if (!mVt) {{
        return false;
    }}
{MOD_DECODE}    vterm_mouse_button(mVt, button, pressed, mod);
    return true;
}}"""

if patch(
    cpp / "Terminal.cpp",
    """bool Terminal::dispatchKey(int modifiers, int key) {""",
    "",  # placeholder; real insertion below
    "dispatchMouseMove",
):
    pass

s = (cpp / "Terminal.cpp").read_text()
if "Terminal::dispatchMouseMove" not in s:
    # Append the implementations just before the extern "C" JNI block.
    jni_anchor = 'Java_org_connectbot_terminal_TerminalNative_nativeDispatchKey'
    idx = s.index(jni_anchor)
    # Walk back to the start of that function's JNIEXPORT line.
    start = s.rindex("JNIEXPORT", 0, idx)
    s = s[:start] + impl.strip() + "\n\n" + s[start:]

    jni = '''
JNIEXPORT jboolean JNICALL
Java_org_connectbot_terminal_TerminalNative_nativeDispatchMouseMove(JNIEnv* /* env */, jobject /* thiz */,
                                                                    jlong ptr, jint row, jint col, jint modifiers) {
    auto* term = reinterpret_cast<Terminal*>(ptr);
    return term->dispatchMouseMove(row, col, modifiers);
}

JNIEXPORT jboolean JNICALL
Java_org_connectbot_terminal_TerminalNative_nativeDispatchMouseButton(JNIEnv* /* env */, jobject /* thiz */,
                                                                      jlong ptr, jint button, jboolean pressed,
                                                                      jint modifiers) {
    auto* term = reinterpret_cast<Terminal*>(ptr);
    return term->dispatchMouseButton(button, pressed != JNI_FALSE, modifiers);
}
'''
    # Insert after nativeDispatchCharacter's closing brace.
    ch = 'Java_org_connectbot_terminal_TerminalNative_nativeDispatchCharacter'
    ci = s.index(ch)
    close = s.index("\n}\n", ci) + len("\n}\n")
    s = s[:close] + jni + s[close:]
    (cpp / "Terminal.cpp").write_text(s)
    changed.append("Terminal.cpp")

# --- TerminalNative.kt: public wrappers + external declarations ------------
k = kt / "TerminalNative.kt"
s = k.read_text()
if "dispatchMouseMove" not in s:
    anchor = """    fun dispatchCharacter(modifiers: Int, character: Int): Boolean {
        checkNotClosed()
        return nativeDispatchCharacter(nativePtr, modifiers, character)
    }"""
    if anchor not in s:
        raise SystemExit("TerminalNative.kt anchor not found")
    s = s.replace(anchor, anchor + '''

    /**
     * Report a mouse move. CodeRelay addition — see
     * linux-terminal/patches/0001-mouse-dispatch.md.
     */
    fun dispatchMouseMove(row: Int, col: Int, modifiers: Int): Boolean {
        checkNotClosed()
        return nativeDispatchMouseMove(nativePtr, row, col, modifiers)
    }

    /**
     * Report a mouse button. Wheel up/down are buttons 4 and 5 by X11
     * convention — the encoding a program in the alternate screen buffer
     * listens for to scroll its own transcript.
     */
    fun dispatchMouseButton(button: Int, pressed: Boolean, modifiers: Int): Boolean {
        checkNotClosed()
        return nativeDispatchMouseButton(nativePtr, button, pressed, modifiers)
    }''', 1)

    decl_anchor = "    private external fun nativeDispatchCharacter(ptr: Long, modifiers: Int, character: Int): Boolean"
    if decl_anchor not in s:
        raise SystemExit("TerminalNative.kt declaration anchor not found")
    s = s.replace(decl_anchor, decl_anchor + """
    private external fun nativeDispatchMouseMove(ptr: Long, row: Int, col: Int, modifiers: Int): Boolean
    private external fun nativeDispatchMouseButton(ptr: Long, button: Int, pressed: Boolean, modifiers: Int): Boolean""", 1)
    k.write_text(s)
    changed.append("TerminalNative.kt")

print("mouse patch:", ", ".join(changed) if changed else "already applied (no-op)")
